// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyrwkzowptobmfsavvij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5cndrem93cHRvYm1mc2F2dmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDczMTQsImV4cCI6MjA1OTg4MzMxNH0.ZXkwlHEDeJ8Pzjck4X56okrp-BeCK5qIfP90FbZk2K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);